### ISSUE TITLE
Code-style formatting doesn't show up in TOC entries

### ISSUE THREAD

**Issue by zetafunction** [google/gitiles#114] opened 2017-09-05 17:34 UTC
## What steps will reproduce the problem?
1. Create a markdown file with the following contents:

```
[TOC]

## Shows up `but this doesn't`
```

2. View the markdown file via gitiles.

## What is the expected output?
The text in backticks should appear in the TOC entry, so the entry reads "Shows up but this doesn't"

## What do you see instead?
It doesn't, and the TOC entry just displays "Shows up"

## Please provide any additional information below.
A live example is https://chromium.googlesource.com/chromium/src/+/master/styleguide/c++/blink-c++.md

**Comment by jrn** [comment] 2019-09-06 16:34
Duplicate of #105.

**Closed by jrn** 2019-09-06 16:34 UTC
