### ISSUE TITLE
feature request: Show timezone on all timestamps

### ISSUE THREAD

**Issue by Alives** [google/gitiles#96] opened 2017-05-05 03:00 UTC
I'm assuming UTC, but it would be nice to be sure (or to have a setting for my browser to show in my local timezone).

Noticed this on author and committer timestamps, there are no zones.

Thanks!
<img width="723" alt="screen shot 2017-05-04 at 7 49 20 pm" src="https://cloud.githubusercontent.com/assets/565994/25732427/45851e3a-3104-11e7-9f85-f2a71a47597c.png">

**Comment by jktjkt** [comment] 2017-09-26 09:26
This looks like a duplicate of #50

**Closed** 2017-10-02 21:40 UTC
