### ISSUE TITLE
Download raw file

### ISSUE THREAD

**Issue by mickaelistria** [google/gitiles#106] opened 2017-06-30 19:04 UTC
It seems like it's not possible to get a raw file from a repo with gitiles with a regular HTTP URL. This is a serious missing feature that currently makes us still need to use cGit.

**Comment by akabrainstorm** [comment] 2017-08-29 12:51
@mickaelistria  Below of the page there is an TXT option for downloading raw file. But downloaded file is base64 encoded. You will need to manually decode it :)

**Comment by mickaelistria** [comment] 2017-08-30 06:37
> You will need to manually decode it :)

That's not a very satisfying answer. Most other Git browsers allow to easily retrieve the content of the file without effort. Gitiles makes it hard.

**Comment by jrtapsell** [comment] 2018-01-08 15:07
If you are in a browser context then this issue may be relevant:
> https://github.com/google/gitiles/issues/119

**Comment by jrn** [comment] 2018-01-08 18:36
Duplicate of #7

**Closed** 2018-01-08 18:37 UTC
Labels: duplicate

**Comment by raymov** [comment] 2019-02-09 09:48
Meanwhile this simple one liner can be used to download & decode a file within a Linux shell, e.g.:
```
# curl "https://android.googlesource.com/device/lge/bullhead/+/master/mixer_paths.xml?format=TEXT"| base64 --decode > mixer_paths.xml
```

**Comment by duduindo** [comment] 2019-07-24 22:12
@raymov , Thank you

**Comment by cuadue** [comment] 2019-10-24 19:36
The curl script does not work with the standard Google setup which uses GSuite for authentication, unless curl somehow signs in using your GSuite Account. Here's your oneliner for vi to open the file downloaded from Gitiles:

    :r!base64 -d /file/downloaded/from/gitiles

Must be an overgeneralization to make sure all files, including binaries, can be transmitted across any communication channel, e.g. websockets, while overlooking (what seems to me) the most common use case.

**Comment by kmturley** [comment] 2019-10-24 23:46
In Node you can use Buffer to decode and display the raw text file:

```
const requestPromise = require('request-promise');
requestPromise.get({
  uri: 'https://example.com/path/file.css?format=TEXT',
  headers: {
    'Authorization': 'Bearer ' + token
  },
  json: false
}).then((resp) => {
  console.log('resp', Buffer.from(resp, 'base64').toString('ascii'));
});
```
