### ISSUE TITLE
Add format=BLOB or fomrat=BINARY to download file content

### ISSUE THREAD

**Issue by alonbl** [google/gitiles#99] opened 2017-05-22 10:24 UTC
Hi,
When reference to a file directly we might want to download it as-is without markdown and/or HTML rendering, for example a configuration file, an mage or a certificate.
This should be simple to achieve if a format is added.
If this is acceptable I will be able to prepare a patch.

As far as I understand this should be applied only to PathServlet::doGetBinary() maybe even hidden Common.soy will not be modified.

Thanks,

**Comment by alonbl** [comment] 2017-05-24 20:40
Hi,
I prepared a patch[1]
Please consider.
Thanks!

[1] https://gerrit-review.googlesource.com/c/107739/

**Comment by jrn** [comment] 2017-12-18 17:20
Duplicate of issue 7.

**Comment by jrn** [comment] 2017-12-18 17:23
Duplicate of #7.

**Comment by jrn** [comment] 2017-12-18 17:24
Duplicate of #7.

**Comment by jrn** [comment] 2017-12-18 17:24
Strange, https://help.github.com/articles/about-duplicate-issues-and-pull-requests/ doesn't seem to be working.

**Closed by jrn** 2017-12-18 17:24 UTC
Labels: duplicate
